[GROUP_KEYWORDS]
manis = manis
depo = manis
kw_1 = mugi

[BRANCH_RULES]
sumo|godong = CV. 
sumo|purwodadi = CV. 

[GENERAL]
gen_new_cust = NOO, Noo

[DIR]
arvi = E:\ADM IRC AND ZN\ARVIEWER.xlsm
arvi_ar_sheet = Source
arvi_name_out = Nama Pelanggan SS
ml_trainning = E:\ADM IRC AND ZN\AR Pusat Machine Learning\ML\Hasil_Latihan.xlsx
save_to_local = E:\ADM IRC AND ZN\2026\AGU\

[AR]
ar_url_irc = https://docs.google.com/spreadsheets/
ar_sheet_irc = Sheet1
ar_key_col_irc = Nama Customer dan Kota 
ar_prod_key_col_irc = 
ar_target_col_irc =  Nominal Nota Belum Lunas 
ar_key_filter_irc = IRC

ar_url_zn = https://docs.google.com/spreadsheets/
ar_sheet_zn = Form Responses 1
ar_key_col_zn =  Nama Customer dan Kota 
ar_prod_key_col_zn = 
ar_target_col_zn =   Nominal Nota Belum Lunas
ar_key_filter_zn = ZN

ar_time_interval = 5
ar_data_fraud = No
ar_data_codecus = Ya
ar_data_namecus = Ya
ar_data_prod = 
ar_data_dt_order = Ya
ar_data_calc = Ya
ar_data_avg_age = No
ar_data_avg_val = No
ar_data_avg_inv = No
ar_data_avg_plaf = Ya
ar_data_avg_pay = Ya
ar_data_avg_his = Ya
ar_data_avg_tier = No
ar_data_inv_numb = No
ar_data_inv_dt = Ya
ar_data_inv_due = Ya
ar_data_inv_val = Ya
ar_data_inv_ar = No
ar_data_inv_orig = Ya
ar_data_inv_pay = No
ar_data_giro = Ya
ar_data_age = Ya
